export const SET_SQUARE_VALUE = "SET_SQUARE_VALUE";
export const INITIALIZE_BOARD = "INITIALIZE_BOARD";

export const SAVE_SETTINGS = "SAVE_SETTINGS";
export const TOGGLE_SETTINGS = "TOGGLE_SETTINGS";

export const APP_GAME_START = "APP_GAME_START";
export const APP_GAME_END = "APP_GAME_END";
export const APP_ONLINE_GAME_START = "APP_ONLINE_GAME_START";
export const APP_ONLINE_GAME_JOIN = "APP_ONLINE_GAME_JOIN";
export const APP_ONLINE_GAME_END = "APP_ONLINE_GAME_END";
export const APP_ONLINE_GAME_RUNNING = "APP_ONLINE_GAME_RUNNING";
export const APP_ONLINE_SET_GAME_ID = "APP_ONLINE_SET_GAME_ID";
export const APP_ONLINE_SET_PLAYER_INFO = "APP_ONLINE_SET_PLAYER_INFO";


export const GAME_RESET = "GAME_RESET";
export const GAME_TURN_CHANGE = "GAME_TURN_CHANGE";
export const GAME_SET_WINNER = "GAME_SET_WINNER";


export const REQUEST_GAMES_LIST = "REQUEST_GAMES_LIST";
export const FAILURE_GAMES_LIST = "FAILURE_GAMES_LIST";
export const RECEIVE_GAMES_LIST = "RECEIVE_GAMES_LIST";

export const GAMES_LIST_HOVER_ROW = "GAMES_LIST_HOVER_ROW";
export const GAMES_LIST_ADD = "GAMES_LIST_ADD";
export const GAMES_LIST_REMOVE = "GAMES_LIST_REMOVE";
