export const SET_SQUARE_VALUE = "SET_SQUARE_VALUE";
export const INITIALIZE_BOARD = "INITIALIZE_BOARD";

export const SAVE_SETTINGS = "SAVE_SETTINGS";
export const TOGGLE_SETTINGS = "TOGGLE_SETTINGS";

export const APP_GAME_START = "APP_GAME_START";
export const APP_GAME_END = "APP_GAME_END";
export const APP_ONLINE_GAME_START = "APP_ONLINE_GAME_START";
export const APP_ONLINE_GAME_END = "APP_ONLINE_GAME_END";


export const GAME_RESET = "GAME_RESET";
export const GAME_TURN_CHANGE = "GAME_TURN_CHANGE";
export const GAME_SET_WINNER = "GAME_SET_WINNER";
