module.exports.APP_ONLINE_GAME_START = "APP_ONLINE_GAME_START";
module.exports.APP_ONLINE_GAME_JOIN = "APP_ONLINE_GAME_JOIN";
module.exports.APP_ONLINE_GAME_END = "APP_ONLINE_GAME_END";
module.exports.APP_ONLINE_GAME_RUNNING = "APP_ONLINE_GAME_RUNNING";
module.exports.APP_ONLINE_SET_PLAYER_INFO = "APP_ONLINE_SET_PLAYER_INFO";
module.exports.APP_ONLINE_SET_GAME_ID = "APP_ONLINE_SET_GAME_ID";
module.exports.APP_ONLINE_SET_GAME_INFO = "APP_ONLINE_SET_GAME_INFO";
module.exports.GAME_TURN_CHANGE = "GAME_TURN_CHANGE";
module.exports.SET_SQUARE_VALUE = "SET_SQUARE_VALUE";


